/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EpochBasedInflationaryVoteToken } from "./EpochBasedInflationaryVoteToken";
export type { EpochBasedInflationaryVoteTokenAbi } from "./EpochBasedInflationaryVoteTokenAbi";
