[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
cache = true
cache_path = "cache"
broadcast = "broadcast"
gas_reports = ["*"]
gas_reports_ignore = []
solc_version = "0.8.26"
optimizer = false
verbosity = 3
ignored_error_codes = []
block_number = 17_740_856
block_timestamp = 1_689_934_508

[profile.production]
evm_version = "cancun"
optimizer = true
optimizer_runs = 999999
build_info = true
sizes = true

[fuzz]
runs = 5_000

[invariant]
runs = 512            # The number of times to run the invariant tests
depth = 25            # The number of calls to make in the invariant tests
call_override = false # Override calls
fail_on_revert = true # Fail the test if the contract reverts
preserve_state = true # Preserve state between invariant files. Active only in conjunction with fail_on_revert true.

[profile.ci]
optimizer = true

[profile.ci.fuzz]
runs = 10_000

[profile.ci.invariant]
runs = 512
depth = 250

[rpc_endpoints]
localhost = "http://127.0.0.1:8545"
sepolia = "https://rpc.sepolia.org"
