/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IGovernor__factory } from "./IGovernor__factory";
export { IGovernorAbi__factory } from "./IGovernorAbi__factory";
