/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  MockEpochBasedVoteTokenAbi,
  MockEpochBasedVoteTokenAbiInterface,
} from "../../Mocks.sol/MockEpochBasedVoteTokenAbi";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epoch_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalSupplyAt_",
        type: "uint256",
      },
    ],
    name: "setTotalSupplyAt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epoch_",
        type: "uint256",
      },
    ],
    name: "totalSupplyAt",
    outputs: [
      {
        internalType: "uint256",
        name: "totalSupply_",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class MockEpochBasedVoteTokenAbi__factory {
  static readonly abi = _abi;
  static createInterface(): MockEpochBasedVoteTokenAbiInterface {
    return new Interface(_abi) as MockEpochBasedVoteTokenAbiInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockEpochBasedVoteTokenAbi {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockEpochBasedVoteTokenAbi;
  }
}
