/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  MockPowerTokenAbi,
  MockPowerTokenAbiInterface,
} from "../../Mocks.sol/MockPowerTokenAbi";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "timepoint_",
        type: "uint256",
      },
    ],
    name: "getPastVotes",
    outputs: [
      {
        internalType: "uint256",
        name: "votePower_",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "delegatee_",
        type: "address",
      },
    ],
    name: "markParticipation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "totalSupplyAt_",
        type: "uint256",
      },
    ],
    name: "setTotalSupplyAt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "votePower_",
        type: "uint256",
      },
    ],
    name: "setVotePower",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epoch_",
        type: "uint256",
      },
    ],
    name: "totalSupplyAt",
    outputs: [
      {
        internalType: "uint256",
        name: "totalSupply_",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class MockPowerTokenAbi__factory {
  static readonly abi = _abi;
  static createInterface(): MockPowerTokenAbiInterface {
    return new Interface(_abi) as MockPowerTokenAbiInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockPowerTokenAbi {
    return new Contract(address, _abi, runner) as unknown as MockPowerTokenAbi;
  }
}
