/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  MockDualGovernorDeployerAbi,
  MockDualGovernorDeployerAbiInterface,
} from "../../Mocks.sol/MockDualGovernorDeployerAbi";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "cashToken_",
        type: "address",
      },
      {
        internalType: "address",
        name: "powerToken_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "proposalFee_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "minProposalFee_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "maxProposalFee_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "reward_",
        type: "uint256",
      },
      {
        internalType: "uint16",
        name: "zeroTokenQuorumRatio_",
        type: "uint16",
      },
      {
        internalType: "uint16",
        name: "powerTokenQuorumRatio_",
        type: "uint16",
      },
    ],
    name: "deploy",
    outputs: [
      {
        internalType: "address",
        name: "deployed_",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "nextDeploy_",
        type: "address",
      },
    ],
    name: "setNextDeploy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class MockDualGovernorDeployerAbi__factory {
  static readonly abi = _abi;
  static createInterface(): MockDualGovernorDeployerAbiInterface {
    return new Interface(_abi) as MockDualGovernorDeployerAbiInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): MockDualGovernorDeployerAbi {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as MockDualGovernorDeployerAbi;
  }
}
