/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC5805__factory } from "./ERC5805__factory";
export { ERC5805Abi__factory } from "./ERC5805Abi__factory";
