/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IDualGovernorDeployer } from "./IDualGovernorDeployer";
export type { IDualGovernorDeployerAbi } from "./IDualGovernorDeployerAbi";
