/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EpochBasedInflationaryVoteTokenHarness__factory } from "./EpochBasedInflationaryVoteTokenHarness__factory";
export { EpochBasedInflationaryVoteTokenHarnessAbi__factory } from "./EpochBasedInflationaryVoteTokenHarnessAbi__factory";
