/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { DualGovernorDeployer } from "./DualGovernorDeployer";
export type { DualGovernorDeployerAbi } from "./DualGovernorDeployerAbi";
