/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EpochBasedVoteTokenHarness__factory } from "./EpochBasedVoteTokenHarness__factory";
export { EpochBasedVoteTokenHarnessAbi__factory } from "./EpochBasedVoteTokenHarnessAbi__factory";
