/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { EpochBasedVoteToken__factory } from "./EpochBasedVoteToken__factory";
export { EpochBasedVoteTokenAbi__factory } from "./EpochBasedVoteTokenAbi__factory";
