/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  MockEpochBasedVoteToken,
  MockEpochBasedVoteTokenInterface,
} from "../../Mocks.sol/MockEpochBasedVoteToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epoch_",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "totalSupplyAt_",
        type: "uint256",
      },
    ],
    name: "setTotalSupplyAt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epoch_",
        type: "uint256",
      },
    ],
    name: "totalSupplyAt",
    outputs: [
      {
        internalType: "uint256",
        name: "totalSupply_",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561000f575f80fd5b5060eb8061001c5f395ff3fe6080604052348015600e575f80fd5b50600436106030575f3560e01c80638f3f63cf146034578063981b24d0146052575b5f80fd5b6050603f3660046080565b5f9182526020829052604090912055565b005b606e605d366004609f565b5f9081526020819052604090205490565b60405190815260200160405180910390f35b5f80604083850312156090575f80fd5b50508035926020909101359150565b5f6020828403121560ae575f80fd5b503591905056fea2646970667358221220175a327f4aafe63352e476a9ae6c7f9180aa4060473e82da3bcb3b93f73f724f64736f6c63430008140033";

type MockEpochBasedVoteTokenConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockEpochBasedVoteTokenConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockEpochBasedVoteToken__factory extends ContractFactory {
  constructor(...args: MockEpochBasedVoteTokenConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string }
  ): Promise<MockEpochBasedVoteToken> {
    return super.deploy(overrides || {}) as Promise<MockEpochBasedVoteToken>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): MockEpochBasedVoteToken {
    return super.attach(address) as MockEpochBasedVoteToken;
  }
  override connect(signer: Signer): MockEpochBasedVoteToken__factory {
    return super.connect(signer) as MockEpochBasedVoteToken__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockEpochBasedVoteTokenInterface {
    return new utils.Interface(_abi) as MockEpochBasedVoteTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockEpochBasedVoteToken {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as MockEpochBasedVoteToken;
  }
}
