/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EpochBasedInflationaryVoteTokenHarness } from "./EpochBasedInflationaryVoteTokenHarness";
export type { EpochBasedInflationaryVoteTokenHarnessAbi } from "./EpochBasedInflationaryVoteTokenHarnessAbi";
