/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IERC6372Abi,
  IERC6372AbiInterface,
} from "../../IERC6372.sol/IERC6372Abi";

const _abi = [
  {
    inputs: [],
    name: "CLOCK_MODE",
    outputs: [
      {
        internalType: "string",
        name: "clockMode",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "clock",
    outputs: [
      {
        internalType: "uint48",
        name: "clock",
        type: "uint48",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IERC6372Abi__factory {
  static readonly abi = _abi;
  static createInterface(): IERC6372AbiInterface {
    return new utils.Interface(_abi) as IERC6372AbiInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC6372Abi {
    return new Contract(address, _abi, signerOrProvider) as IERC6372Abi;
  }
}
