/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRegistrar__factory } from "./IRegistrar__factory";
export { IRegistrarAbi__factory } from "./IRegistrarAbi__factory";
