/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  MockPowerToken,
  MockPowerTokenInterface,
} from "../../Mocks.sol/MockPowerToken";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "timepoint_",
        type: "uint256",
      },
    ],
    name: "getPastVotes",
    outputs: [
      {
        internalType: "uint256",
        name: "votePower_",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "delegatee_",
        type: "address",
      },
    ],
    name: "markParticipation",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "totalSupplyAt_",
        type: "uint256",
      },
    ],
    name: "setTotalSupplyAt",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "votePower_",
        type: "uint256",
      },
    ],
    name: "setVotePower",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "epoch_",
        type: "uint256",
      },
    ],
    name: "totalSupplyAt",
    outputs: [
      {
        internalType: "uint256",
        name: "totalSupply_",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101a6806100206000396000f3fe608060405234801561001057600080fd5b50600436106100675760003560e01c8063981b24d011610050578063981b24d0146100a9578063c580b269146100be578063ea86e118146100cf57600080fd5b8063093ed4901461006c5780633a46b1a814610081575b600080fd5b61007f61007a3660046100e2565b600055565b005b61009761008f366004610124565b505060005490565b60405190815260200160405180910390f35b6100976100b73660046100e2565b5060015490565b61007f6100cc36600461014e565b50565b61007f6100dd3660046100e2565b600155565b6000602082840312156100f457600080fd5b5035919050565b803573ffffffffffffffffffffffffffffffffffffffff8116811461011f57600080fd5b919050565b6000806040838503121561013757600080fd5b610140836100fb565b946020939093013593505050565b60006020828403121561016057600080fd5b610169826100fb565b939250505056fea2646970667358221220ffc3d8aba8716cc022c41e952eda92e4e78ace16865c577c3c3f0c0f12bf467364736f6c63430008130033";

type MockPowerTokenConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockPowerTokenConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockPowerToken__factory extends ContractFactory {
  constructor(...args: MockPowerTokenConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string }
  ): Promise<MockPowerToken> {
    return super.deploy(overrides || {}) as Promise<MockPowerToken>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): MockPowerToken {
    return super.attach(address) as MockPowerToken;
  }
  override connect(signer: Signer): MockPowerToken__factory {
    return super.connect(signer) as MockPowerToken__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockPowerTokenInterface {
    return new utils.Interface(_abi) as MockPowerTokenInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockPowerToken {
    return new Contract(address, _abi, signerOrProvider) as MockPowerToken;
  }
}
